services:
  # API Service
  api:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html

  # VPN Server
  vpn-server:
    build:
      context: .
      dockerfile: ./docker/vpn-server/Dockerfile
    privileged: true
    ports:
      - "1194:1194/udp"

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=vpn4u
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql

  # Redis for Caching and Sessions
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  # Admin Dashboard
  admin-dashboard:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public/admin:/usr/share/nginx/html

volumes:
  mysql-data: